language: python
python:
    - 2.7
    - 2.6
    - 2.5
env:
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.3.1
    - DJANGO_VERSION=1.2.7
before_install:
    - export DJANGO_SETTINGS_MODULE="tests.settings"
install:
    - pip install --use-mirrors Django==$DJANGO_VERSION
    - python setup.py -q install
script: django-admin.py test gcframe --settings="gcframe.tests.settings"
