# After any modifications to this file, be sure to check it with
# http://lint.travis-ci.org/

language: python
python:
    - 3.3
    - 3.2
    - 2.7
    - 2.6
env:
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.3.7
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.5
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.2
      env: DJANGO_VERSION=1.4.5
    - python: 3.2
      env: DJANGO_VERSION=1.3.7
before_install:
    - export DJANGO_SETTINGS_MODULE="gcframe.tests.settings"
install:
    - pip install --use-mirrors Django==$DJANGO_VERSION
    - python setup.py -q install
script: django-admin.py test gcframe
